name: Build and Deploy Android App
on:
  push:
    branches:
      - main
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
      - name: Get dependencies
        run: flutter pub get
      - name: Build app bundle
        run: flutter build appbundle
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: android/app/build/outputs/bundle/release/app-release.aab
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag: ${{ github.sha }}
          name: Android App Release
          body: Automated release from GitHub Actions